### ISSUE TITLE
Cockpit port clash 

### ISSUE THREAD

**Issue by mysqlboy** [bmildren/mysql-monitoring#1]
Running on Fedora23 where I've got `cockpit` running also clashes with the port mapping into the prometheus container.

```
[moore@george mysql-monitoring]$ docker-compose -f monitor.yml up -d
Starting grafana_data
Starting prometheus_data
Starting percona_grafana_pre
Starting influx_data
percona_influxdb is up-to-date
Starting percona_prometheus
ERROR: failed to create endpoint percona_prometheus on network mysqlmonitoring_dbnode: Error starting userland proxy: listen tcp 0.0.0.0:9090: bind: address already in use
```

Seeing this is the port that cockpit listens on by default and will likely 'be there' before you get around to this test.

```
sudo netstat -alnp | grep 9090
[sudo] password for moore: 
tcp6       0      0 :::9090                 :::*                    LISTEN      1/systemd 
```

**Comment by mysqlboy** [comment]
I suggest just a documentation update here. It's obviously no issue with this setup but could be a known pre-req. 

```
sudo systemctl stop cockpit.service cockpit.socket
```

**Comment by bmildren** [comment]
Fixed with https://github.com/bmildren/mysql-monitoring/commit/ff2eb4b9331c66aac187c6ce1097f30550c89598
